[package]
name = "elven-nft-minter-meta"
version = "1.12.0"
authors = ["Julian Ćwirko <julian.io>"]
edition = "2021"
publish = false

[dependencies.elven-nft-minter]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.39.2"
