[package]
name = "elven-nft-minter-meta"
version = "1.11.0"
authors = ["Julian Ćwirko <julian.io>"]
edition = "2021"
publish = false

[dependencies.elven-nft-minter]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.38.0"
